codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: up
  range: "50...90"
  status:
    project:
      default:
        threshold: 0.042%
    patch:
      default:
        target: 65%